ci: run tests on OS X and Windows
xJonathanLEI/starknet-rs pull request #24
Opened 2022-01-12 21:13 UTC by milancermak

Resolves #23

2022-01-12 21:23 UTC, milancermak commented
This [initial run](https://github.com/xJonathanLEI/starknet-rs/actions/runs/1689743489) was rather long, but I think that's because there was no cache hit, subsequent runs should be faster.

2022-01-13 04:46 UTC, xJonathanLEI requested changes
In the test command you're missing the `--target` flag on Windows, which results in `msvc` always being tested on both variants. Using `actions-rs/toolchain@v1` won't automatically set that up.

2022-01-13 04:52 UTC, xJonathanLEI commented
Not sure if that applies to `stable`/`nightly` too. You might have to use `cargo +nightly test` on nightly channels. For this one I haven't tested yet though.

The `--target` one, on the other hand, has indeed been tested, and explicitly specifying it is needed.

2022-01-13 08:44 UTC, xJonathanLEI approved these changes
Nice job 🚀

2022-01-13 08:44 UTC, merged

2022-01-13 08:57 UTC, milancermak commented
Cheers, and thank you for spotting the error in the first place.