feat: explicit BlockId::Latest
xJonathanLEI/starknet-rs pull request #57
Opened 2022-02-02 17:01 UTC by milancermak

This PR replaces the use of `Option<BlockId>` with an explicit `BlockId::Latest` variant, as discussed in point 4) in #53.

2022-02-02 19:05 UTC, xJonathanLEI requested changes
The code changes look good 👍🏻

But the example in README won't compile after the change, as `BlockId` is not in scope.

2022-02-02 20:05 UTC, milancermak commented
Well spotted. Should be good now.

2022-02-03 06:07 UTC, xJonathanLEI requested changes
It still doesn't compile lol. One extra bracket for the 3rd example.

2022-02-03 06:10 UTC, xJonathanLEI commented
And I fixed it for you :))

2022-02-03 06:11 UTC, xJonathanLEI approved these changes

2022-02-03 06:19 UTC, merged